### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by patroclo77** [AdaCore/RC_Car_Demo#2]
Hi,
I got this error when compiling against the library:

Builder results
    C:\Users\..\RC_Car_Demo-master\src\engine_control.adb
        8:6 "Engine_Control (body)" depends on "Vehicle (body)"
        8:6 "Recursive_Moving_Average_Filters_Discretes (spec)" depends on "Sequential_Bounded_Buffers (spec)"
        8:6 "Vehicle (body)" depends on "Recursive_Moving_Average_Filters_Discretes (spec)"
        8:6 file "sequential_bounded_buffers.ads" not found
    C:\Users\..\Robotics_with_Ada\src\signal_processing\recursive_moving_average_filters_discretes.ads
        56:8 "Sample_Data" is undefined (more references follow)
        55:31 "Sequential_Bounded_Buffers" is undefined
        59:48 incorrect constraint for this kind of type

Project
    C:\Users\s..\RC_Car_Demo-master\Ada_Drivers_Library\boards\stm32f407_discovery\stm32f407_discovery_full.gpr
        59:24 warning: library directory "C:\Users\sam\Documents\Spark_Project\RC_Car_Demo-master\Ada_Drivers_Library\boards\stm32f407_discovery\obj\full_lib_Debug\" does not exist
        58:23 warning: object directory "obj/full_Debug" not found

How can I solve it?

**Comment by pat-rogers** [comment]
The package Sequential_Bounded_Buffers should be (is) in the Robotics_with_Ada\src\utils\ folder. Is it not there in your copy?

**Comment by patroclo77** [comment]
It had to be something like that. I've updated "Robotics_with_Ada" folder and now everything is working. Many thanks :)

**Comment by pat-rogers** [comment]
Glad to hear that!  
You're very welcome.
